app:
  version: @project.version@

debug: false

logging:
  level:
    root: ERROR
  pattern:
    console:

spring:
  datasource:
    embedded-database-connection: h2
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:~/h2test;AUTO_SERVER=true
#    username: sa
#    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
#    generate-ddl: false
    show-sql: false
  sql:
    init:
      mode: always
      schema-locations: classpath:create-table.sql
      data-locations: classpath:insert-address-*.sql